#define IDC_MYICON                      2
#define IDC_BTN_LOAD                    3
#define IDC_BTN_UNLOAD                  4
#define IDC_BTN_EXTRACT                 5
#define IDC_PCT_BOX                     6
#define IDC_BTN_SAVE                    7
#define IDC_CB_DRAW						8
#define	IDC_CB_POSTPROC					9
#define IDD_TEXTRECOGNITION_DIALOG      102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_STRING104                   104
#define IDM_EXIT                        105
#define IDI_TEXTRECOGNITION             107
#define IDI_SMALL                       108
#define IDC_TEXTRECOGNITION             109
#define IDS_LABELS                      110
#define IDM_OPEN						111
#define IDM_SAVE						112
#define IDM_CLOSE						113
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     356
#define IDB_BITMAP2                     357
#define IDB_BITMAP3                     358
#define IDB_BITMAP4                     359
#define IDB_BITMAP5                     360
#define IDB_BITMAP6                     361
#define IDB_BITMAP7                     362
#define IDB_BITMAP8                     363
#define IDB_BITMAP9                     364
#define IDB_BITMAP10                    365
#define IDB_BITMAP11                    366
#define IDB_BITMAP12                    367
#define IDB_BITMAP13                    368
#define IDB_BITMAP14                    369
#define IDB_BITMAP15                    370
#define IDB_BITMAP16                    371
#define IDB_BITMAP17                    372
#define IDB_BITMAP18                    373
#define IDB_BITMAP19                    374
#define IDB_BITMAP20                    375
#define IDB_BITMAP21                    376
#define IDB_BITMAP22                    377
#define IDB_BITMAP23                    378
#define IDB_BITMAP24                    379
#define IDB_BITMAP25                    380
#define IDB_BITMAP26                    381
#define IDB_BITMAP27                    382
#define IDB_BITMAP28                    383
#define IDB_BITMAP29                    384
#define IDB_BITMAP30                    385
#define IDB_BITMAP31                    386
#define IDB_BITMAP32                    387
#define IDB_BITMAP33                    388
#define IDB_BITMAP34                    389
#define IDB_BITMAP35                    390
#define IDB_BITMAP36                    391
#define IDB_BITMAP37                    392
#define IDB_BITMAP38                    393
#define IDB_BITMAP39                    394
#define IDB_BITMAP40                    395
#define IDB_BITMAP41                    396
#define IDB_BITMAP42                    397
#define IDB_BITMAP43                    398
#define IDB_BITMAP44                    399
#define IDB_BITMAP45                    400
#define IDB_BITMAP46                    401
#define IDB_BITMAP47                    402
#define IDB_BITMAP48                    403
#define IDB_BITMAP49                    404
#define IDB_BITMAP50                    405
#define IDB_BITMAP51                    406
#define IDB_BITMAP52                    407
#define IDB_BITMAP53                    408
#define IDB_BITMAP54                    409
#define IDB_BITMAP55                    410
#define IDB_BITMAP56                    411
#define IDB_BITMAP57                    412
#define IDB_BITMAP58                    413
#define IDB_BITMAP59                    414
#define IDB_BITMAP60                    415
#define IDB_BITMAP61                    416
#define IDB_BITMAP62                    417
#define IDB_BITMAP63                    418
#define IDB_BITMAP64                    419
#define IDB_BITMAP65                    420
#define IDB_BITMAP66                    421
#define IDB_BITMAP67                    422
#define IDC_STATIC                      -1

// Next default values for new objects
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        424
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
